# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmLogin(object):
    def setupUi(self, frmLogin):
        frmLogin.setObjectName("frmLogin")
        frmLogin.resize(698, 327)
        self.centralwidget = QtWidgets.QWidget(frmLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.frameLogin = QtWidgets.QFrame(self.centralwidget)
        self.frameLogin.setGeometry(QtCore.QRect(10, 10, 421, 301))
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.labelInformed = QtWidgets.QLabel(self.frameLogin)
        self.labelInformed.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelInformed.setFont(font)
        self.labelInformed.setObjectName("labelInformed")
        self.groupBoxLogin = QtWidgets.QGroupBox(self.frameLogin)
        self.groupBoxLogin.setGeometry(QtCore.QRect(10, 70, 401, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBoxLogin.setFont(font)
        self.groupBoxLogin.setObjectName("groupBoxLogin")
        self.labelUserName = QtWidgets.QLabel(self.groupBoxLogin)
        self.labelUserName.setGeometry(QtCore.QRect(10, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelUserName.setFont(font)
        self.labelUserName.setObjectName("labelUserName")
        self.lineEditUsername = QtWidgets.QLineEdit(self.groupBoxLogin)
        self.lineEditUsername.setGeometry(QtCore.QRect(120, 30, 271, 31))
        self.lineEditUsername.setObjectName("lineEditUsername")
        # self.lineEditUsername.text()
        self.labelPassword = QtWidgets.QLabel(self.groupBoxLogin)
        self.labelPassword.setGeometry(QtCore.QRect(10, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.lineEditPassword = QtWidgets.QLineEdit(self.groupBoxLogin)
        self.lineEditPassword.setGeometry(QtCore.QRect(120, 100, 271, 31))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.btnLogin = QtWidgets.QPushButton(self.frameLogin)
        self.btnLogin.setGeometry(QtCore.QRect(130, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLogin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon)
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(self.frameLogin)
        self.btnExit.setGeometry(QtCore.QRect(280, 240, 121, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon1)
        self.btnExit.setObjectName("btnExit")
        self.frameUserType = QtWidgets.QFrame(self.centralwidget)
        self.frameUserType.setGeometry(QtCore.QRect(450, 10, 241, 131))
        self.frameUserType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUserType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUserType.setObjectName("frameUserType")
        self.label = QtWidgets.QLabel(self.frameUserType)
        self.label.setGeometry(QtCore.QRect(30, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cbUsers = QtWidgets.QComboBox(self.frameUserType)
        self.cbUsers.setGeometry(QtCore.QRect(30, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbUsers.setFont(font)
        self.cbUsers.setToolTipDuration(-1)
        self.cbUsers.setIconSize(QtCore.QSize(30, 30))
        self.cbUsers.setObjectName("cbUsers")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/admin-ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbUsers.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/teacher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbUsers.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/student.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbUsers.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/staff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbUsers.addItem(icon5, "")
        frmLogin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(frmLogin)
        self.statusbar.setObjectName("statusbar")
        frmLogin.setStatusBar(self.statusbar)

        self.retranslateUi(frmLogin)
        self.cbUsers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmLogin)

    def retranslateUi(self, frmLogin):
        _translate = QtCore.QCoreApplication.translate
        frmLogin.setWindowTitle(_translate("frmLogin", "frmLogin"))
        self.labelInformed.setText(_translate("frmLogin", "Log In or Create an Account"))
        self.groupBoxLogin.setTitle(_translate("frmLogin", "Login"))
        self.labelUserName.setText(_translate("frmLogin", "User name"))
        self.labelPassword.setText(_translate("frmLogin", "Password"))
        self.btnLogin.setText(_translate("frmLogin", "Login"))
        self.btnExit.setText(_translate("frmLogin", "Exit"))
        self.label.setText(_translate("frmLogin", "Select user to login"))
        self.cbUsers.setItemText(0, _translate("frmLogin", "Admin"))
        self.cbUsers.setItemText(1, _translate("frmLogin", "Professor"))
        self.cbUsers.setItemText(2, _translate("frmLogin", "Student"))
        self.cbUsers.setItemText(3, _translate("frmLogin", "Staff"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmLogin = QtWidgets.QMainWindow()
    ui = Ui_frmLogin()
    ui.setupUi(frmLogin)
    frmLogin.show()
    sys.exit(app.exec_())
